// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv4GJA8wS_nF3gNJpFayQYTmUHEw-9PGo',
    appId: '1:531158953289:android:c0fd2485ff98b87e437e98',
    messagingSenderId: '531158953289',
    projectId: 'pilot-38a0f',
    storageBucket: 'pilot-38a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2bKfaWgK8gnfg1mAPm8ZOCuPqltfz3f0',
    appId: '1:531158953289:ios:0418f5b73e86234a437e98',
    messagingSenderId: '531158953289',
    projectId: 'pilot-38a0f',
    storageBucket: 'pilot-38a0f.firebasestorage.app',
    androidClientId: '531158953289-gpbb8icb34vhn3dcm121thd894il1ktr.apps.googleusercontent.com',
    iosClientId: '531158953289-8fics4f0p8mg7l9eogjvjmbdu1rjo9j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilotProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ueb3DYVs8UTI8O3KnZrUxQ3vwCKhufg',
    appId: '1:531158953289:web:efe7390c5681d79d437e98',
    messagingSenderId: '531158953289',
    projectId: 'pilot-38a0f',
    authDomain: 'pilot-38a0f.firebaseapp.com',
    storageBucket: 'pilot-38a0f.firebasestorage.app',
    measurementId: 'G-T5Z5QFTZ7H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2bKfaWgK8gnfg1mAPm8ZOCuPqltfz3f0',
    appId: '1:531158953289:ios:0418f5b73e86234a437e98',
    messagingSenderId: '531158953289',
    projectId: 'pilot-38a0f',
    storageBucket: 'pilot-38a0f.firebasestorage.app',
    androidClientId: '531158953289-gpbb8icb34vhn3dcm121thd894il1ktr.apps.googleusercontent.com',
    iosClientId: '531158953289-8fics4f0p8mg7l9eogjvjmbdu1rjo9j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pilotProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ueb3DYVs8UTI8O3KnZrUxQ3vwCKhufg',
    appId: '1:531158953289:web:afeffae6a27e33df437e98',
    messagingSenderId: '531158953289',
    projectId: 'pilot-38a0f',
    authDomain: 'pilot-38a0f.firebaseapp.com',
    storageBucket: 'pilot-38a0f.firebasestorage.app',
    measurementId: 'G-XMG6KX07ME',
  );

}